### ISSUE TITLE
Prepare 0.015 release

### ISSUE THREAD

**Issue by karpet** [karpet/dezi-app#13]
Pushed a dev release with all recent changes to http://matrix.cpantesters.org/?dist=Dezi-App%200.014_01

**Comment by karpet** [comment]
latest: http://matrix.cpantesters.org/?dist=Dezi-App%200.014_02

**Comment by karpet** [comment]
@paultcochrane I am tracking dev releases here to make sure I'm using Dist::Zilla ok and cpan is happy.

**Comment by karpet** [comment]
0.015 is released!

**Comment by paultcochrane** [comment]
Yay! :-)
